// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU9xjhlRM2JvVAWQWmCpsJNs93NYlY1aw',
    appId: '1:112842842073:web:58fec6fe96754b9cc043c8',
    messagingSenderId: '112842842073',
    projectId: 'ccchat-tfg',
    authDomain: 'ccchat-tfg.firebaseapp.com',
    storageBucket: 'ccchat-tfg.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIlXO2HQZoHW7el4lMZJMbgL6vRzRBlqs',
    appId: '1:112842842073:android:0aa408ccf07b4647c043c8',
    messagingSenderId: '112842842073',
    projectId: 'ccchat-tfg',
    storageBucket: 'ccchat-tfg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyd2c3Ub-DyH_WM4h66DblOld-BFFUOv4',
    appId: '1:112842842073:ios:61e37d66ea6bc2a2c043c8',
    messagingSenderId: '112842842073',
    projectId: 'ccchat-tfg',
    storageBucket: 'ccchat-tfg.appspot.com',
    iosClientId: '112842842073-n7qkr7n9cblera1grlm2bant2f6ukdp0.apps.googleusercontent.com',
    iosBundleId: 'com.example.ccchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyd2c3Ub-DyH_WM4h66DblOld-BFFUOv4',
    appId: '1:112842842073:ios:61e37d66ea6bc2a2c043c8',
    messagingSenderId: '112842842073',
    projectId: 'ccchat-tfg',
    storageBucket: 'ccchat-tfg.appspot.com',
    iosClientId: '112842842073-n7qkr7n9cblera1grlm2bant2f6ukdp0.apps.googleusercontent.com',
    iosBundleId: 'com.example.ccchat',
  );
}
